export const ProjObjOne = {
    id: 'projects',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'Pathfinding Visualizer',
    headline: '✨ Featured Work',
    firstParagraph: "Hello, I'm Jonny Lie. I am a recent graduate student from UTS and I am based in Sydney. I like to work with React.js, Java and Node.js but I am always open to learning new technology",
    techStacks: "React.js, Bootstrap",
    imgStart: true,
    img: require('../../images/Pathfinding-Visualizer-Project.PNG').default,
    alt: 'Pathfinding-Visualizer-Project',
    dark: false,
    primary: false,
    darkText: false,

    lightBg2: false,
    lightText2: true,
    lightTextDesc2: true,
    topLine2: 'MLBB Pro',
    headline2: '✨ Featured Work',
    firstParagraph2: "Hello, I'm Jonny Lie. I am a recent graduate student from UTS and I am based in Sydney. I like to work with React.js, Java and Node.js but I am always open to learning new technology",
    techStacks2: "React.js, Bootstrap",
    imgStart2: false,
    img2: require('../../images/MLBBPro-Project.PNG').default,
    alt2: 'MLBBPro-Project',
    dark2: false,
    primary2: true,
    darkText2: false,

    techStacks2: "React.js, Bootstrap",
    img3: require('../../images/WonderEats-Project.PNG').default,
    imgStart3: true,

}
