export const ProjObjOne = {
    id: 'projects',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'Pathfinding Visualizer',
    headline: '✨ Featured Work',
    firstParagraph: "Web application for visualizing Pathfinding algorithms in actions. A pathfinding algorithm is used to find the shortest path between two points (start point and end point). Implemented Dijkstra, A* Search, Depth-first Search and Breadth-first Search.",
    techStacks: "React.js, CSS, Bootstrap",
    imgStart: true,
    img: require('../../images/Pathfinding-Visualizer-Project.PNG').default,
    alt: 'Pathfinding-Visualizer-Project',
    pathName: 'https://jonnylie.github.io/Pathfinding-Visualizer/',
    gitPathName: 'https://github.com/Jonnylie/Pathfinding-Visualizer',
    dark: false,
    primary: false,
    darkText: false,
    gitIconMarginLeft: true,

    lightBg2: false,
    lightText2: true,
    lightTextDesc2: true,
    topLine2: 'MLBB Pro',
    headline2: '✨ Featured Work',
    firstParagraph2: "Responsive website to give detailed information about Mobile Legends game and teach people who are interested in playing the game.",
    techStacks2: "React/Redux, CSS, Webpack, React Router",
    imgStart2: false,
    img2: require('../../images/MLBBPro-Project.PNG').default,
    alt2: 'MLBBPro-Project',
    pathName2: 'https://mlpro.netlify.com',
    gitPathName2: 'https://github.com/Jonnylie/MLPro',
    dark2: false,
    primary2: true,
    darkText2: false,
    gitIconMarginLeft: true,

    topLine3: 'WonderEats',
    firstParagraph3: "Mobile application for ordering food online from Indonesian restaurants in Sydney. Builds an android application for restaurants and customers. Implemented food order, order history, view foods by category, search menu, authentication, login, cart, email notification and payment system.",
    techStacks3: "Kotlin, Node.js, Cloud Firestore, Nodemailer, Android SDK, Firebase Cloud Function, Stripe, XML",
    img3: require('../../images/WonderEats-Project.PNG').default,
    alt3: 'WonderEats-Project',
    pathName3: 'https://youtu.be/s7T7RTb051A',

    topLine4: 'My Porfolio',
    firstParagraph4: "Fully responsive react portfolio using React Hooks and Styled Components. This project highlights my recent projects and introduces more about myself",
    techStacks4: "React.js, React Hooks, Styled Components, React Router, CSS",
    img4: require('../../images/My-Portfolio-Project.PNG').default,
    alt4: 'My-Portfolio-Project',
    pathName4: 'https://jonnylie.netlify.app/',
    gitPathName4: 'https://github.com/Jonnylie/react-portfolio',
    gitIconMarginLeft: true,

    topLine5: 'Online Movie Store',
    firstParagraph5: "MVC based web application for users to buy movies and admin to manage movies and users. My responsibility for this project is to Create RESTful APIs to handle user login, authentication and login/logout history",
    techStacks5: "Java, HTML, Bootstrap, SQL",
    img5: require('../../images/Online-Movie-Store-Project.jpg').default,
    alt5: 'Online-Movie-Store-Project',
    gitPathName5: 'https://github.com/Jonnylie/Online-Movie-Store',
    gitIconMarginLeft2: false,
}
